### ISSUE TITLE
verifyRequest is always returning false

### ISSUE THREAD

**Issue by Neokyuubi** [albertcht/invisible-recaptcha#100]
Hello,

Can i use InvisibleReCaptcha::verifyRequest as an Extra step of Checking ?

And of course this works just fine.
```
$validate = Validator::make(Input::all(),
[
    'g-recaptcha-response' => 'required|captcha',
]);
```
i was just wondering if verifyRequest can be helpful if i want to check that the gCaptcha is coming from one of the domains that i filled when registering the keys for the invisible captcha.
I

I'm using Laravel 5.5, but InvisibleReCaptcha::verifyRequest(\request) in my controller is always returning false.

**Comment by albertcht** [comment]
You may need to collect other info by yourself because it only calls google's api return the response for you.
