### ISSUE TITLE
Doesn't works with my Laravel Auth :(

### ISSUE THREAD

**Issue by MrFallen** [albertcht/invisible-recaptcha#106]
Controller:
![image](https://user-images.githubusercontent.com/5339386/54216462-6a44fc80-4535-11e9-89f6-efc5762b572f.png)
View:
![image](https://user-images.githubusercontent.com/5339386/54216493-79c44580-4535-11e9-8540-b52dbf3d5da4.png)

After clicking the Registration button, nothing happens.

Who can help me? :(

**Comment by aFluxx** [comment]
There's probably an error somewhere;

Try to display messages and you'll probably learn what is happening. You could try to print something like this on the page:

```
@if(count($errors) > 0)
    @foreach($errors->all() as $error)
        <div class="alert alert-danger">
            {{ $error }}
        </div>
    @endforeach
@endif
```
