### ISSUE TITLE
INVISIBLE_RECAPTCHA_BADGEHIDE=true squaks a bit with Vue

### ISSUE THREAD

**Issue by aFluxx** [albertcht/invisible-recaptcha#107]
Hello there,

I have split up `@captchaHTML `&` @captchaScripts` so that Laravel + Vue doesn't throw any errors.
But the problem arises again if you set `INVISIBLE_RECAPTCHA_BADGEHIDE` to true.

This implements the following code in the template:
`<style>.grecaptcha-badge{display:none;!important}</style>`

Any chance we can render this out of the template (maybe with a blade directive in the header).
Right now I solved this by manually putting it in my stylesheet.

This is the Vue error:
`- Templates should only be responsible for mapping the state to the UI. Avoid placing tags with side-effects in your templates, such as <style>, as they will not be parsed.`

**Comment by albertcht** [comment]
Hi @aFluxx ,
Hi @aFluxx ,

I think the best way to hide the badge in vue is to turn `INVISIBLE_RECAPTCHA_BADGEHIDE` off. And apply `<style>.grecaptcha-badge{display:none;!important}</style>` in your vue files.
