### ISSUE TITLE
Undefined variable: lang

### ISSUE THREAD

**Issue by hocklai8** [albertcht/invisible-recaptcha#109]
Using @captchaPolyfill gives this undefined variable: lang

I believe there's a bug in InvinsibleReCaptchaServiceProvider addBladeDirective() Line 78 missing a $lang parameter
```
$blade->directive('captchaPolyfill', function ($lang) {
     return "<?php echo app('captcha')->renderPolyfill({$lang}); ?>";
});
```

**Comment by albertcht** [comment]
@hocklai8 ,

Thanks for your report, I've fixed it in the release `v1.9.2`.
