### ISSUE TITLE
cURL error 60: SSL certificate problem

### ISSUE THREAD

**Issue by BAKTETE** [albertcht/invisible-recaptcha#12]
unable to get local issuer certificate (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)

**Comment by ConsoleTVs** [comment]
I don't think you can use a self-signed ssl with google while developing

**Comment by BAKTETE** [comment]
i'm not using any self-signed ssl

**Comment by BAKTETE** [comment]
it's working fine now i'va updated curl in php.ini to use cacert.pem
`curl.cainfo ="C:\wamp64\cacert.pem"`

link to `cacert.pem` [https://curl.haxx.se/ca/cacert.pem](url)

**Comment by ConsoleTVs** [comment]
Ah sure, nice!
