### ISSUE TITLE
Add support for Laravel 8

### ISSUE THREAD

**Issue by Kaishiyoku** [albertcht/invisible-recaptcha#138]
Laravel 8 was released today (https://packagist.org/packages/laravel/framework#v8.0.0)

**Comment by paulocastellano** [comment]
Waiting for that :)

**Comment by rickmills** [comment]
https://github.com/albertcht/invisible-recaptcha/pull/136#pullrequestreview-488397069 

Tested and ready to merge

**Comment by pjebs** [comment]
@albertcht can we merge this?

**Comment by azrahn** [comment]
Looks like this package isn't maintained anymore.
But its luckily very easy to make your own with Laravel view components.

**Comment by michaloravec** [comment]
@albertcht Could you merge #136 It's just a few seconds for you.

**Comment by rickmills** [comment]
@albertcht appears to have abandoned the project sadly so I doubt this'll be merged. Several prominent projects that relied on it have now moved to alternatives so that might be the best course of action.

**Comment by michaloravec** [comment]
@rickmills Could you post some alternatives for that?

**Comment by azrahn** [comment]
If you want you can just fork the repository and merge yourself.

**Comment by rutgergrasgroen** [comment]
Im also curious about the other alternatives. @rickmills

**Comment by rickmills** [comment]
This was the most popular one: https://github.com/anhskohbo/no-captcha
