### ISSUE TITLE
Two captcha protected forms on a single page

### ISSUE THREAD

**Issue by navise** [albertcht/invisible-recaptcha#14]
There's a scenario where I have two forms on a page. I want to protect both the forms with invisible captcha. Both forms are hidden as the page loads and are displayed in a lightbox on a user action. How do I use this plugin in this case?

**Comment by albertcht** [comment]
Maybe you can try to render two captchas in each submit form.

**Comment by albertcht** [comment]
This package implements only the most common case - single recaptcha form in one page, but you can write your client side code yourself. The server side validation still works in your case. 
You can refer to this article: [How to add multiple invisible recaptcha in single page?](https://stackoverflow.com/questions/43231850/how-to-add-multiple-invisible-recaptcha-in-single-page) to give it a try.
