### ISSUE TITLE
Setting to captcha false not working

### ISSUE THREAD

**Issue by warmwhisky** [albertcht/invisible-recaptcha#146]
Since I renewed my local ssl certificate I can no longer access the login page. it throws 
`Too few arguments to function AlbertCht\InvisibleReCaptcha\InvisibleReCaptchaServiceProvider::AlbertCht\InvisibleReCaptcha\{closure}(), 1 passed and exactly 2 expected`

Disabling captcha on login does not work from both ENV and config.access.
I do not cache my config or route in local.

Restarting Apache no avail. Restarting chrome no avail

The only way to get to the login page is to physically delete the captcha code in the login page.

**Comment by albertcht** [comment]
Hi @warmwhisky  ,

It's been fixed in release `v1.9.5`
