### ISSUE TITLE
recaptcha sends double reload request

### ISSUE THREAD

**Issue by DanDvoracek** [albertcht/invisible-recaptcha#156]
Hi there,

I've been searching for a while and can't figure out what happens really. 

I have a very basic frontend setup with a contact page for which I'd like to use this package.
Everything is fine with the form (method, @csrf, @captcha, etc...) and the data is indeed validated with a custom request class. Validation passes and flash message is sent accordingly. I then save the data in DB, usual stuff. 

**The problem is that every time I submit the form I end up with two entries in my DB for the same submission**. I searched for mistakes in my code before realising that the invisible-recaptcha sends two xhr requests, which is probably why I end up with two records...

Is that the normal lifecycle ? Is there a way to avoid this behaviour ? As I said, my setup is a standard form page as you would except regarding the markup. Very standard stuff. The request class too. Nothing wrong there as data validates correctly.

Any hint would be appreciated. Thanks!

// Laravel 9 - php 8

![Screenshot 2022-02-16 at 11 47 38](https://user-images.githubusercontent.com/1983331/154249064-03569dc9-5270-4c56-957a-1fe8375439e7.png)

**Comment by brandonyoungdev** [comment]
Did you ever find a fix for this?
