### ISSUE TITLE
Captcha not loading in IE 11

### ISSUE THREAD

**Issue by ddensted** [albertcht/invisible-recaptcha#19]
I'm running into an issue where the Captcha does not load in IE so on form submission it always returns "The g-recaptcha-response field is required". This problem is exclusive to IE and when viewing the console in IE there is an error message. `SCRIPT5: Access is denied.`

**Comment by albertcht** [comment]
hi @ddensted 
This bug should be fixed in the newest release version v1.5. Can you update your package and try it again?
