### ISSUE TITLE
Incompatibility with laravel-jsvalidation

### ISSUE THREAD

**Issue by marcelogarbin** [albertcht/invisible-recaptcha#24]
Laravel: 5.4
invisible-recaptcha: "dev-master@dev";
with package: https://github.com/proengsoft/laravel-jsvalidation

Using laravel-jsvalidation, when clicking the submit button the form is sent, even the fields are required. If I comment on the invisible-recaptcha code, the form behaves normally.

**Comment by albertcht** [comment]
@marcelogarbin 
Because the js rendered by this package will listen to the submit event, and do the captcha validation before submiting your form. However, in your case, your other package might listen to the submit event as well, but the control has been taken to my listen function.
You can try to implement a customization function to check if it works.
```
_submitEvent = function() {
    $('#YourFormId').valid();
    _submitForm();
}
```

**Comment by marcelogarbin** [comment]
Hi @albertcht , that worked! The form was validated without being sent, it was only sent after completing the information in the fields. 

I tested it on Chrome and Firefox.

Is this code in the body of the page (added manually), or is it possible to do something so that both plugins work accordingly without conflict?

Thank you very much for your attention.

**Comment by marcelogarbin** [comment]
Unfortunately I came back with this problem, I noticed that when opening the browser console the code that you gave me as help returns me an infinite Loop. I have no idea how to solve it.

`Uncaught RangeError: Maximum call stack size exceeded.`

How can I find the source of the problem? Do you have an idea?

**Comment by marcelogarbin** [comment]
Problem solved in https://github.com/albertcht/invisible-recaptcha/issues/38#issuecomment-327489537
