### ISSUE TITLE
Provide way to disable in tests

### ISSUE THREAD

**Issue by mkarnicki** [albertcht/invisible-recaptcha#30]
Hi, thanks for you sweet package.

Can we provide a way to disable this in tests? I tried the following:
`app('captcha')->shouldReceive('verifyRequest')->andReturn(true);`

but for some reason I'm getting:

`call to undefined method shouldReceive()`

I don't get it, because InvisibleReCaptcha extends `Facade`, so it should have that method. Any advice? For now, I did a nasty trick:

`$this->app['validator']->extend('captcha', function () {
            return true;
        });`

**Comment by oppenheimer** [comment]
Thank you Albertcht as well, for a great package.

@mkarnicki Have you considered using the Google "test keys"? 
[https://developers.google.com/recaptcha/docs/faq](https://developers.google.com/recaptcha/docs/faq)

**Comment by mkarnicki** [comment]
@oppenheimer Sorry for late reply. Thank you, I should have done a better search. This is exactly what I needed. Closing the issue.
