### ISSUE TITLE
trying to use recaptcha in a bootstrap modal.

### ISSUE THREAD

**Issue by ItzMe42** [albertcht/invisible-recaptcha#31]
Hello, I'm using your recaptcha class and it works well, great work! However I'm trying to use it on my website. To be more specific, I'm using it inside a bootstrap modal and the captcha works but the captcha label is aligned weird. Like it's buggin back and forth at the right border of the modal. I thought it will fix inside the normal page body like in the right corner. I know I can hide it but the biggest problem is, that the page speed is stroooongly reduced by using recaptcha. Is there any style inside your class where I can float / align the google label to another place? I've red that the reason cames from using a model.

**Comment by albertcht** [comment]
hi @ItzMe42 , Do you mean it will slow down your page load speed if you're trying to hide the recaptcha badge? You can try to overwtire recaptcha css to make it fit in a modal.

**Comment by albertcht** [comment]
Hi @ItzMe42  , in version 1.7, I have added a config called INVISIBLE_RECAPTCHA_DATABADGE that you can customize your css style.
There are three different styles available: bottomright,bottomleft, inline
