### ISSUE TITLE
Issue with multiple forms using captcha in the same page

### ISSUE THREAD

**Issue by martinsce** [albertcht/invisible-recaptcha#34]
Hello,
I have multiple forms in the same page that uses invisible reCaptcha the issue with this library 
is that when rendering the captcha using 

    {!! app('captcha')->render(); !!}

It creates a `_g-recaptcha` id

     <div id="_g-recaptcha"></div>
 
and also loads https://www.google.com/recaptcha/api.js script

if you could simple change `_g-recaptcha` to use a class  and load the script once with some other way like `app('captcha')->init()`. Multi form support should work perfectly.

For the time being i will try to do it manually in the frontend without using `app('captcha')->render()` method, but i hope that you will support this in the future.

**Comment by albertcht** [comment]
hi @martinsce
Great suggestion, I have marked this issue as a new milestone, but I can't guarantee when it will be completed.

**Comment by mikeymatteo** [comment]
Probably a horrible way to achieve it but I've just tested it will this for the render function

```
public function render($lang = null, string $multipleRendered = null)
    {
        $html = '';
        if(!$multipleRendered) {
            $html .= '<script src="' . $this->getPolyfillJs() . '"></script>' . PHP_EOL;
        }
        $html .= '<div id="_g-recaptcha' . $multipleRendered . '"></div>' . PHP_EOL;
        if ($this->hideBadge) {
            $html .= '<style>.grecaptcha-badge{display:none;!important}</style>' . PHP_EOL;
        }
        $html .= '<div class="g-recaptcha" data-sitekey="' . $this->siteKey .'"';
        $html .= 'data-size="invisible" data-callback="_submitForm"></div>';
        if(!$multipleRendered) {
            $html .= '<script src="' . $this->getCaptchaJs($lang) . '" async defer></script>' . PHP_EOL;
        }
        $html .= '<script>var _submitForm,_captchaForm,_captchaSubmit;</script>';
        $html .= '<script>window.onload=function(){';
        $html .= '_captchaForm=document.querySelector("#_g-recaptcha' . $multipleRendered . '").closest("form");';
        $html .= "_captchaSubmit=_captchaForm.querySelector('[type=submit]');";
        $html .= '_submitForm=function(){if(typeof _submitEvent==="function"){_submitEvent();';
        $html .= 'grecaptcha.reset();}else{_captchaForm.submit();}};';
        $html .= "_captchaForm.addEventListener('submit',";
        $html .= "function(event){event.preventDefault();grecaptcha.execute();});";
        if ($this->debug) {
            $html .= $this->renderDebug();
        }
        $html .= "}</script>" . PHP_EOL;

        return $html;
    }
```

and then instantiated with `{!! app('captcha')->render(null, "SomeUnqiueValueHERE"); !!}`

**Comment by albertcht** [comment]
thank you @mikeymatteo , I will check it.

**Comment by mikeymatteo** [comment]
I think it will also need
`&render=explicit`

```
if(!$multipleRendered) {
            $html .= '<script src="' . $this->getCaptchaJs($lang) . '&render=explicit" async defer></script>' . PHP_EOL;
        }
```

**Comment by mikeymatteo** [comment]
On second look, there is a little more to it than that. I don't get much spare time but if i come up with a good solution before you have, i'll submit a pull request.

**Comment by albertcht** [comment]
Hello @martinsce @mikeymatteo , I created a new branch for multi-forms purpose. You can go check it out to see if it meets your needs.

**Comment by marcelogarbin** [comment]
@martinsce @mikeymatteo Were you able to use multiple forms with this package?
