### ISSUE TITLE
Config for data-badge parameter

### ISSUE THREAD

**Issue by mind-io** [albertcht/invisible-recaptcha#35]
Hi All,
Nice package. But default reCAPTCHA badge position is ignoring any page structure and goes under my bootstrap sticky footer and not visible :/
So we need to be able to pass `data-badge` with **inline** value and have some styling options.

BR

**Comment by albertcht** [comment]
hi @mind-io,
Have you considered to hide the badge by setting `INVISIBLE_RECAPTCHA_BADGEHIDE=true`?
The style of reCAPTCHA badge is generated by Google, and there's no way to change it via its api unless you override its css style on your own.

**Comment by mind-io** [comment]
Yes, that's exactly what I did at the moment. And what I meant  by styling is more about control where to position the badge.

**Comment by albertcht** [comment]
hi @mind-io,
after reading offical api document, I found there's a `data-badge` parameter and it allows:
bottomright, bottomleft, inline 3 different options to style your badge.
I will add another env config for users to pass their `data-badge` value to rendered function in next release.

**Comment by albertcht** [comment]
Hi @mind-io , in version 1.7, I have added a config called `INVISIBLE_RECAPTCHA_DATABADGE` that you can customize your css style.
There are three different styles available: `bottomright`,` bottomleft`, `inline`
