### ISSUE TITLE
Process other Laravel validation rule first

### ISSUE THREAD

**Issue by subdesign** [albertcht/invisible-recaptcha#36]
Is it possible somehow to process other Laravel validation rules first? For example if I have an email field, and it's required, recaptcha shouldn't "fire" only if a valid email entered..

**Comment by albertcht** [comment]
Hi @subdesign , according to your description, I think you need to do frontend validation or simply just use native required attribute. For example:
```html
<input type="text" name="email" required>
```

**Comment by subdesign** [comment]
Thanks
