### ISSUE TITLE
_captchaForm.submit is not a function

### ISSUE THREAD

**Issue by JoshMountain** [albertcht/invisible-recaptcha#39]
I'm getting this error after implementing this package on a simple form. Debug says everything is binding properly however it won't submit the form.

<img width="423" alt="screen shot 2017-08-24 at 1 13 02 pm" src="https://user-images.githubusercontent.com/3465855/29686518-1a3bea5c-88ce-11e7-8fd4-b398e16814bd.png">

**Comment by albertcht** [comment]
hi @JoshMountain , sorry for responding late.
Can you provide the code how you render with this package? It will be helpful to figure out this situation.
