### ISSUE TITLE
The g-recaptcha-response field is required

### ISSUE THREAD

**Issue by sektonic** [albertcht/invisible-recaptcha#4]
I get error when submit button like "The g-recaptcha-response field is required"

**Comment by albertcht** [comment]
That means your captcha request didn't send to google properly. Did you see the badge logo on the right-bottom side? If not, you might render your captcha in a wrong way. You can post the code how you render your captcha in your view that I can have more info about your issue.

**Comment by kmg101** [comment]
I'm getting the same error and I do see the badge logo on the right-bottom side. Seems like something is missing

**Comment by albertcht** [comment]
Can you dump the request inputs before validation? Check if there's a `g-recaptcha-response` parameter first. If not, can you also post your full html of the form including how you render captcha section here? I will add debug feature to the next release to help users figure out if they render the captcha correctly.

**Comment by albertcht** [comment]
Hi, this issue should be fixed in newer version v1.2. can you update your package and try it again? thanks!

**Comment by kmg101** [comment]
Thanks, I will update and let you know

**Comment by albertcht** [comment]
hi, there. I close this issue because this bug should have been fixed.
you can open another issue if you have other questions, thanks.
