### ISSUE TITLE
I don't understand the installation guide

### ISSUE THREAD

**Issue by frenchqwerty** [albertcht/invisible-recaptcha#42]
> Validation

> Add 'g-recaptcha-response' => 'required|captcha' to rules array.

```

$validate = Validator::make(Input::all(), [
    'g-recaptcha-response' => 'required|captcha'
]);
```
Where do I add this on my laravel project ?

Thank you

**Comment by albertcht** [comment]
hi @frenchqwerty , there are many ways to use validator in Laravel, please see https://laravel.com/docs/5.5/validation
