### ISSUE TITLE
Multiple re-catpchas on page throws ERRORS - ReCAPTCHA placeholder element must be empty

### ISSUE THREAD

**Issue by PhPPgAdminBug** [albertcht/invisible-recaptcha#45]
Hello, thank you for your cool package.

I have issue with multiple re captchas on single page. I have 3 forms, login, registration and reset password.

2 of them hidde, when you click button, appears form we need. I do not want to do this with ajax or async loading forms. Because user can loop it and do bad stuff to server, loading forms. So i think this is bad practice to do like that.

When i use `     @captcha($lang = null)` on all my 3 forms, it show 2 error for other 2 form. So only 1 re-captcha works, other to not.

**ERROR**
`Uncaught Error: ReCAPTCHA placeholder element must be empty
    at nr (recaptcha__ru.js:473)
    at recaptcha__ru.js:478
    at c (recaptcha__ru.js:468)`

**How to fix it? Or i should try visible captcha? Will it work?**

**Comment by albertcht** [comment]
hi @PhPPgAdminBug , may I ask which branch you are using now? You should use `multi-forms` branch instead of `master` branch.

**Comment by PhPPgAdminBug** [comment]
thank you,  installed package with command  `composer require albertcht/invisible-recaptcha`

**Comment by albertcht** [comment]
hi @PhPPgAdminBug , you can refer to this issue: #46

**Comment by PhPPgAdminBug** [comment]
Wow, it breaks all other scripts. After we typed command `composer require albertcht/invisible-recaptcha:dev-multi-forms`  **it breaks other JS packages like jquery ui, bootstrap scripts, tether etc.**

Ofcourse it is related only to this pard of code. `{{-- Invisible Google Recaptcha --}}
                        @captcha()` that renders capthca.

it seems somehow it breaks all script that go before....
`  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script>var _renderedTimes,_captchaCallback,_captchaForms,_submitForm,_submitBtn;</script><script>var _submitAction=true,_captchaForm;</script><script>$.getScript('https://www.google.com/recaptcha/api.js?onload=_captchaCallback&render=explicit').done(function(data,status,jqxhr){_renderedTimes=$("._g-recaptcha").length;_captchaForms=$("._g-recaptcha").closest("form");_captchaForms.each(function(){$(this)[0].addEventListener("submit",function(e){e.preventDefault();_captchaForm=$(this);_submitBtn=$(this).find(":submit");grecaptcha.execute();});});_submitForm=function(){_submitBtn.trigger("captcha");if(_submitAction){_captchaForm.submit();}};_captchaCallback=function(){grecaptcha.render("_g-recaptcha_"+_renderedTimes,{sitekey:'{6Lca1jEUAAAAANuZaEaD0KpNjXxnzyTCOPX3iMT-}',size:'invisible',callback:_submitForm});}});</script>
<style>.grecaptcha-badge{display:none;!important}</style>
<div class="_g-recaptcha" id="_g-recaptcha_1"><div class="grecaptcha-badge" style="width: 256px; height: 60px; transition: right 0.3s ease; position: fixed; bottom: 14px; right: -186px; box-shadow: gray 0px 0px 5px;"><div class="grecaptcha-logo"><iframe src="https://www.google.com/recaptcha/api2/anchor?k=%7B6Lca1jEUAAAAANuZaEaD0KpNjXxnzyTCOPX3iMT-%7D&amp;co=aHR0cDovL2dyYWJnZy5hcHA6ODA.&amp;hl=ru&amp;v=r20171003155951&amp;size=invisible&amp;cb=jxabtedr2du" title="виджет reCAPTCHA" width="256" height="60" frameborder="0" scrolling="no" sandbox="allow-forms allow-popups allow-same-origin allow-scripts allow-top-navigation allow-modals allow-popups-to-escape-sandbox"></iframe></div><div class="grecaptcha-error"></div><textarea id="g-recaptcha-response" name="g-recaptcha-response" class="g-recaptcha-response" style="width: 250px; height: 40px; border: 1px solid #c1c1c1; margin: 10px 25px; padding: 0px; resize: none;  display: none; "></textarea></div></div>`

**Comment by albertcht** [comment]
hi @PhPPgAdminBug , can you post your error message here to help me figure out what's going on? I'm doubting you're using an elder version jquery in your original project, and it caused conflict(not sure).
And it doesn't support Vue.js, I will suggest you to find other recaptcha solutions for VueJS.

**Comment by PhPPgAdminBug** [comment]
Error message says for every jQuery function, that is not a function. 
Smth like `$().func is not a function`.

**Comment by albertcht** [comment]
Hi @PhPPgAdminBug , I did some changes to this branch. From now on, you need to include `jquery` before you call the captcha. I also provide an example repo to demonstrate how to use this branch with an ajax usage. You can check: https://github.com/albertcht/invisible-recaptcha-example/tree/multi-forms

**Comment by marcelogarbin** [comment]
@PhPPgAdminBug Were you able to use multiple forms with this package?
