### ISSUE TITLE
Cannot read property 'querySelector' of null we need custom views

### ISSUE THREAD

**Issue by johnnymast** [albertcht/invisible-recaptcha#48]
Hello Sir,

On laravel 5.4 it was running fine but on 5.5 i get this error .

![screen shot 2017-10-25 at 23 15 59](https://user-images.githubusercontent.com/121194/32023754-91ac47a2-b9da-11e7-9134-25a4ff6ca187.png)

It relates tho the following code:

![screen shot 2017-10-25 at 23 17 32](https://user-images.githubusercontent.com/121194/32023819-b8e14250-b9da-11e7-9862-95aaeca13f97.png)

I think i will help you out with this and also add overwritable views for this project. I need this because in 5.4 it hindered me because the javascript was loaded of http while it should be :// so the browser can deside it self.

**Comment by johnnymast** [comment]
PS the error can be found here https://opensource.nl2nd.com/ ..

**Comment by johnnymast** [comment]
also this project isnt done yet ;) it will find opensource projects for beginners. Like issues with labels as "great for beginners" and "easy"

**Comment by albertcht** [comment]
hi @johnnymast, I just visited your website, and I can't find any form element in your html script. The captcha must be rendered in a form element.

**Comment by ctf0** [comment]
@albertcht i have the same issue, its related to vue which cant have a script tag inside its controlled container, so i have to move the captcha outside of it which means it will be outside of any form boundaries, 
am using axios for submit so i dont think the captcha needs to be inside the form or am i wrong, if yes then is there a way around to get to work with vue properly ?
