### ISSUE TITLE
Failed to load resource: the server responded with a status of 400 ()

### ISSUE THREAD

**Issue by BAKTETE** [albertcht/invisible-recaptcha#49]
the package was working fine suddenly it start throwing `400`

![untitled](https://user-images.githubusercontent.com/27772375/32169260-b452208e-bd67-11e7-9764-1c0b56f82616.png)

**Comment by albertcht** [comment]
hi @BAKTETE, it looks like your data-key is wrong, you put `{6LcRwCQUAAAAAAcCl5p4...}` in your config, please remove`{`, `}` marks.

**Comment by BAKTETE** [comment]
@albertcht this is the url to my website [messagerie.ump.ma](messagerie.ump.ma)
