### ISSUE TITLE
Uncaught Error: The bind parameter must be an element or id recaptcha__en.js:380

### ISSUE THREAD

**Issue by arminneman** [albertcht/invisible-recaptcha#5]
```
<div id="_g-recaptcha"></div>
<div class="g-recaptcha" data-sitekey="x" data-bind="send-btn" data-callback="_submitForm"></div><script src="https://www.google.com/recaptcha/api.js" async defer></script>

<script>var _submitForm,_captchaForm,_captchaSubmit;</script>
<script>
window.onload=function(){_captchaForm=document.querySelector("#_g-recaptcha").closest("form");
_captchaSubmit=_captchaForm.querySelector('[type=submit]');
_submitForm=function(){if(typeof _submitEvent==="function"){_submitEvent();grecaptcha.reset();}else{_captchaForm.submit();
}}}
</script>

this is the HTML generated by  {!! app('captcha')->render() !!}
```

the g-recaptcha-response in $_REQUEST comes back empty as well.

**Comment by albertcht** [comment]
thanks for your bug report! you help me find a fatal bug in the render function. now this bug is fixed in v1.2. you can update your package and try it again. feel free to open another issue if you have other questions :)

**Comment by arminneman** [comment]
Hi Albertcht, thanks for the quick reply. The binding error is gone. You seem to have fixed that part. However the g-recaptcha-response still comes in empty. I hope you can work it out with the new details.

<form role="form" method="POST" action="https://auth.dev/login" class="form-horizontal"><input type="hidden" name="_token" value="KHLzvZb6BOA61MG4xFefWu6jWSTEL8KDB07oWqG7"> <div id="_g-recaptcha"></div> <div data-sitekey="xxx" data-size="invisible" data-callback="_submitForm" class="g-recaptcha"><div class="grecaptcha-badge" style="width: 256px; height: 60px; transition: right 0.3s ease; position: fixed; bottom: 14px; right: -186px; box-shadow: gray 0px 0px 5px;"><div class="grecaptcha-logo"><iframe src="https://www.google.com/recaptcha/api2/anchor?k=6LeyqyAUAAAAAIi5ucv8znn-o_pGQbA5PdIRPUJP&amp;co=aHR0cHM6Ly9hdXRoLmRldjo0NDM.&amp;hl=en&amp;v=r20170503135251&amp;size=invisible&amp;cb=nja0h83l0dda" title="recaptcha widget" width="256" height="60" frameborder="0" scrolling="no" name="undefined"></iframe></div><div class="grecaptcha-error"></div><textarea id="g-recaptcha-response" name="g-recaptcha-response" class="g-recaptcha-response" style="width: 250px; height: 40px; border: 1px solid #c1c1c1; margin: 10px 25px; padding: 0px; resize: none;  display: none; "></textarea></div></div> <div class="form-group"><label for="email" class="col-md-4 control-label">E-Mail Address</label> <div class="col-md-6"><input id="email" type="email" name="email" value="xxx" required="required" autofocus="autofocus" class="form-control"></div></div> <div class="form-group"><label for="password" class="col-md-4 control-label">Password</label> <div class="col-md-6"><input id="password" type="password" name="password" required="required" class="form-control"></div></div> <div class="form-group"><div class="col-md-6 col-md-offset-4"><div class="checkbox"><label><input type="checkbox" name="remember" checked="checked"> Remember Me
                                    </label></div></div></div> <div class="form-group"><div class="col-md-8 col-md-offset-4"><button type="submit" class="btn btn-primary">
                                    Login
                                </button> <a href="https://auth.dev/password/reset" class="btn btn-link">
                                    Forgot Your Password?
                                </a></div></div></form>

**Comment by albertcht** [comment]
thanks one more time, i have fixed this bug. the version code is still v1.2. you can update your package and try it again :)

**Comment by arminneman** [comment]
I have actually updated the package. The formatting is a bit messy, but if you would compare the two pieces of code I provided in my last post you can see that the output of your package is different now. Just to be sure I have also done a clear and update afterwards. But the problem remains.

C:\laragon\www\Auth>composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 0 installs, 4 updates, 0 removals
  - Updating laravel/framework (v5.4.22 => v5.4.23): Downloading (100%)
  - Updating albertcht/invisible-recaptcha (v1.1 => v1.2): Downloading (100%)
  - Updating laravelcollective/html (v5.4.1 => v5.4.3): Downloading (100%)
  - Updating psy/psysh (v0.8.3 => v0.8.4): Downloading (100%)
Writing lock file
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postUpdate
> php artisan optimize
Generating optimized class loader
The compiled services file has been removed.

C:\laragon\www\Auth>composer clear-cache
Clearing cache (cache-dir): C:\Users\Arminneman\AppData\Local\Composer
Clearing cache (cache-files-dir): C:\Users\Arminneman\AppData\Local\Composer\files
Clearing cache (cache-repo-dir): C:\Users\Arminneman\AppData\Local\Composer\repo
Cache directory does not exist (cache-vcs-dir):
All caches cleared.

C:\laragon\www\Auth>composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 0 installs, 1 update, 0 removals
  - Updating psy/psysh (v0.8.4 => v0.8.5): Downloading (100%)
Writing lock file
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postUpdate
> php artisan optimize
Generating optimized class loader
The compiled services file has been removed.

**Comment by albertcht** [comment]
check your composer.lock file, does the reference code equal to `34586edba0eaa6b73bdce6212a73e5c18c3310e5` of albertcht/invisible-recaptcha? if not, delete composer.lock and run `composer install`

**Comment by arminneman** [comment]
"dist": {
                "type": "zip",
                "url": "https://api.github.com/repos/albertcht/invisible-recaptcha/zipball/34586edba0eaa6b73bdce6212a73e5c18c3310e5",
                "reference": "34586edba0eaa6b73bdce6212a73e5c18c3310e5",
                "shasum": ""
            },

**Comment by albertcht** [comment]
ok, you could open the browser console, and then type those following variables to observe if they are correctly bound:
_captchaForm
_captchaSubmit
and execute `grecaptcha.execute();` to see if your form will be submited.

**Comment by arminneman** [comment]
yes, that works, It just doesn't work if I hit the submit button instead.



_captchaForm
<form role=​"form" method=​"POST" action=​"http:​/​/​auth.dev/​login" class=​"form-horizontal">​…​</form>​
_captchaSubmit
<button type=​"submit" class=​"btn btn-primary">​
                                    Login
                                ​</button>​


and grecaptcha.execute(); will submit the form.

**Comment by albertcht** [comment]
if you're using chrome, also type `getEventListeners(_captchaSubmit)` in the console to check if the click event attached to your submit button

**Comment by arminneman** [comment]
```
getEventListeners(_captchaSubmit)
Object {click: Array(1)}
click
:
Array(1)
__proto__
:
Object
```

**Comment by albertcht** [comment]
all right, let me clarify your issue again...
1. will the form be submitted after you click your submit button now?
2. if yes, will you get the `g-recaptcha-response` request from the backend?
3. if you trigger `grecaptcha.execute()` manually, everything works fine?

**Comment by arminneman** [comment]
1/2. Form submits, but no g-recaptcha-response, causing validation to fail.
3.  Yes. This works.

**Comment by albertcht** [comment]
can you go check your `vendor/albertcht/invisible-recaptcha/src/InvisibleReCaptcha.php` to see what `line 87` looks like?

**Comment by arminneman** [comment]
```
   /**
     * Render HTML reCaptcha by optional language param.
     *
     * @return string
     */
    public function render($lang = null)
    {
        $html = '<div id="_g-recaptcha"></div>' . "\n";
        if ($this->hideBadge) {
            $html .= '<style>.grecaptcha-badge{display:none;!important}</style>' . "\n";
        }
        $html .= '<div class="g-recaptcha" data-sitekey="' . $this->siteKey .'" ';
        $html .= 'data-bind="send-btn" data-callback="_submitForm"></div>';
        $html .= '<script src="' . $this->getJs($lang) . '" async defer></script>' . "\n";
        $html .= '<script>var _submitForm,_captchaForm,_captchaSubmit;</script>';
        $html .= '<script>window.onload=function(){';
        $html .= '_captchaForm=document.querySelector("#_g-recaptcha").closest("form");';
        $html .= "_captchaSubmit=_captchaForm.querySelector('[type=submit]');";
        $html .= '_submitForm=function(){if(typeof _submitEvent==="function"){_submitEvent();';
        $html .= 'grecaptcha.reset();}else{_captchaForm.submit();}}}</script>' . "\n";

        return $html; //<<line 87
    }
```

**Comment by albertcht** [comment]
ok, i found the problem. your file is still in old version due to unknown reason. delete your composer.lock and vendor folder. run composer install again.

**Comment by arminneman** [comment]
no, I just copy pasted from the wrong project :) That's why i removed my comment right away =) But that's not the problem.

**Comment by albertcht** [comment]
no, it's the old code. in newer version. it should be
```
$html .= "function(event){event.preventDefault();grecaptcha.execute();});}</script>" . "\n";
```
on line87

**Comment by arminneman** [comment]
yes, sorry you're right. I did copy paste from the old project, that's why I was confused. I copy pasted right from the source now and that seems to work :). Will try to get composer to get the right files. Thanks alot for your time.

**Comment by albertcht** [comment]
no problem, thanks for your bug reporting as well 👍
