### ISSUE TITLE
Using recaptcha with ajax submitted forms

### ISSUE THREAD

**Issue by keevitaja** [albertcht/invisible-recaptcha#51]
Hello!

Is there a easy, or not so easy, way to make recaptcha work with ajax forms where data is posted using axios library?

**Comment by albertcht** [comment]
Hi @keevitaja, please see https://github.com/albertcht/invisible-recaptcha#customize-submit-function. You can use axios in `_submitEvent` function directly to submit an ajax form.

**Comment by keevitaja** [comment]
tnx... this actually is pretty simple from scratch too.
