### ISSUE TITLE
Console error in blade.php file

### ISSUE THREAD

**Issue by jrod730** [albertcht/invisible-recaptcha#53]
When including the "@captcha" console displays a warning with the following:

app.js:sourcemap:44258 [Vue warn]: Error compiling template:

- Templates should only be responsible for mapping the state to the UI. Avoid placing tags with side-effects in your templates, such as <script>, as they will not be parsed.
- Templates should only be responsible for mapping the state to the UI. Avoid placing tags with side-effects in your templates, such as <style>, as they will not be parsed.
- Templates should only be responsible for mapping the state to the UI. Avoid placing tags with side-effects in your templates, such as <script>, as they will not be parsed.
- Templates should only be responsible for mapping the state to the UI. Avoid placing tags with side-effects in your templates, such as <script>, as they will not be parsed.
- Templates should only be responsible for mapping the state to the UI. Avoid placing tags with side-effects in your templates, such as <script>, as they will not be parsed.

Any ideas on how to fix this? When "@captcha" is removed the error disappears.

**Comment by albertcht** [comment]
hi @jrod730 ,

When you call "@captcha", the package will generate js script to bind your button submit event. However, this kind of behavior is not recommended by Vue. You should implement your frontend captcha by yourself of use other packages like https://github.com/MicroDroid/vue-invisible-recaptcha

Nevertheless, you can still remain this package for your backend captcha validation.
