### ISSUE TITLE
How test formValidation

### ISSUE THREAD

**Issue by willsilvano** [albertcht/invisible-recaptcha#54]
Hi.

I'm getting this error: 
`Illuminate\Validation\ValidationException: The given data was invalid.`

How can I send the captcha validation to my controller?

**Comment by albertcht** [comment]
Hi @willsilvano ,

If you're asking how to do the validation in form request, just add `'g-recaptcha-response' => 'required|captcha'` to your rules.

**Comment by willsilvano** [comment]
Hi @albertcht !
My problem is how test this in test class.
`$this->post(route('my.route'), $data)`
How I should send the param `g-recaptcha-response` in the `$data`?

**Comment by albertcht** [comment]
Hi @willsilvano ,

In this case you need to mock `InvisibleReCaptcha` by yourself.
Here is the example how you can do it.
```
$this->post(route('my.route'), [
    'g-recaptcha-response' => '1',
    // your other data
]);

InvisibleReCaptcha::shouldReceive('verifyResponse')
    ->once()
    ->andReturn(true);
```

**Comment by willsilvano** [comment]
@albertcht Thank you man! It's working now!

**Comment by willsilvano** [comment]
@albertcht Thank you man! It's working now!

**Comment by langeuh** [comment]
I'd like to add the following:

if you use `$this->visit()` instead of `$this->post()`to test your page, you'll need to add following snippet as well:

```php
        InvisibleReCaptcha::shouldReceive('render')
            ->andReturn('<input type="hidden" name="g-recaptcha-response" value="1">');
```
