### ISSUE TITLE
not works with laravel auth 

### ISSUE THREAD

**Issue by rolandverner** [albertcht/invisible-recaptcha#56]
i try to put the recaptha to registration and that not works with it

**Comment by albertcht** [comment]
Hi @rolandverner ,

Please provide more detail information for clarifying your question. For example, the web console message or the partial code how you use this package in your view.

**Comment by rolandverner** [comment]
![image](https://user-images.githubusercontent.com/12708415/34319103-b751a026-e7e1-11e7-882e-567721930a84.png)
![image](https://user-images.githubusercontent.com/12708415/34319107-cc7496a2-e7e1-11e7-9783-7b000ef520ac.png)
![image](https://user-images.githubusercontent.com/12708415/34319109-d6f6e8c8-e7e1-11e7-9697-99dac6b723db.png)

**Comment by albertcht** [comment]
Hi @rolandverner ,

According to your screenshots, the captcha has been successfully loaded because the badge logo is shown on your right-bottom side.

You can dump your form data on the backend to check if there's a `g-recaptcha-response` field. If yes, that means the captcha works properly.

**Comment by rolandverner** [comment]
it still not works on laravel auth

**Comment by rolandverner** [comment]
Can be that it have some conflict with other packages?

**Comment by albertcht** [comment]
There's a full laravel boilerplate project you can refer to:
https://github.com/Labs64/laravel-boilerplate

That boilerplate project integrates this package in its registration page and use laravel auth as well.

**Comment by alariva** [comment]
Be aware that captcha error is silent if validation messages are not printed.

```
                                @captcha
                                @if ($errors->has('g-recaptcha-response'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('g-recaptcha-response') }}</strong>
                                    </span>
                                @endif
```
So maybe is just the captcha check what is failing, possibly due to bad site/secret key.
It happened to me (as silly as it seems) that before copy-paste my double-click selection excluded the very last character (for example a `-` symbol), and it can pass unnoticed. Make sure you are performing tests with the very right keys configured.
