### ISSUE TITLE
Blade directive @captcha with language

### ISSUE THREAD

**Issue by MichalOravec** [albertcht/invisible-recaptcha#57]
Hi,

there is problem with @captcha.

To work it is necessary to specify a constant and not a string

`@captcha(en)`

instead of

`@captcha('en')`

This work great:

`{!! app('captcha')->render(app()->getLocale()) !!}`

but this not:

@captcha(app()->getLocale())

**Comment by albertcht** [comment]
Hi @MichalOravec ,

Thanks for your bug report.
It's designed to put a string in this function, and I released a hotfix to fix this bug: https://github.com/albertcht/invisible-recaptcha/releases/tag/v1.8.1
