### ISSUE TITLE
Fail Test

### ISSUE THREAD

**Issue by timgavin** [albertcht/invisible-recaptcha#60]
My badge shows in the bottom corner of the page, so I assume it's working correctly. However, I'd like to make it fail on purpose so I can see what happens. Is this possible? I'm using Laravel 5.5.

Thank you for this package! :)

**Comment by albertcht** [comment]
Hi @timgavin ,
I'm not sure the meaning of 'make it fail'. You can try to send your request via postman or other alternative tools directly. Then you should get the result as you expect.

**Comment by timgavin** [comment]
OK, Was just looking for a way to make sure it's actually working by seeing an error message or something like what a bot would get.
