### ISSUE TITLE
What is polyfill.js used for?

### ISSUE THREAD

**Issue by whitea2** [albertcht/invisible-recaptcha#63]
What is the purpose of "https://cdn.polyfill.io/v2/polyfill.min.js" ? 

I noticed on the polyfill.js site that it is no longer maintained. Can I safely comment the following to remove the need for polyfill.min.js?
`$html = '<script src="' . $this->getPolyfillJs() . '"></script>' . PHP_EOL;" `

**Comment by albertcht** [comment]
Hi @whitea2,

polyfill.js is for patching unsupported js apis for old browsers (like IE). And as far as I know, polyfill.js is still under maintainacne.
