### ISSUE TITLE
Overrides jQuery Validate and submits an invalid form

### ISSUE THREAD

**Issue by magnosis** [albertcht/invisible-recaptcha#64]
Hi there,

I use this in conjunction with jQuery Validate, provided by [proengsoft/laravel-jsvalidation ](https://github.com/proengsoft/laravel-jsvalidation).

It seems that whenever I add @captcha() to my forms, these forms now submit even when invalid.

As soon as I remove the @captcha() line from the form, then the form behaves as expected, and will not submit if jQuery.validate({}) fails validation.

Any help would be appreciated. How do I prevent invisible-recaptcha to override .validate() and submit my form when it's invalid?

**Comment by magnosis** [comment]
I fixed this one myself, adding this bit of JS to forms that use both laravel-jsvalidation and invisible-recaptcha:

```
$(document).ready(function () {
     // See if recaptcha appears on this form
    if($('#myform .g-recaptcha').length) {
        // This callback is used in the JS generated by @captcha()
        _beforeSubmit = function() { 
            // Don't run validation again, just check it.
            // Returning false won't submit the form.
            return $('#myform').validate().checkForm(); 
        }
    }
});
```

**Comment by elijahpaul** [comment]
I'm still seeing the reCaptcha fire even with an invalid form!
![invisible_recaptcha_jquery_validation_laravel](https://user-images.githubusercontent.com/478088/42546481-74ad71ca-84b5-11e8-9223-6378d309f14d.gif)
What am I doing wrong? Where does the `_submitEvent` go?
```
$(document).on('submit', '#submit-btn', function () {
    if ($('#myform .g-recaptcha').length) {
        _beforeSubmit = function() {        
            return $('#myform').valid(); 
        },
        _submitEvent = function() {
            $.ajax({
                url: '/signup',
                type: 'POST',
                data: {
                    "_token": $('input[name="_token"]').val(),
                    "name": $('#name').val(),
                    "email": $('#email').val(),
                    "password": $('#password').val(),
                    "g-recaptcha-response": $("#g-recaptcha-response").val(),
                },
                success: function(data) {
                    console.log(data);                
                },
                error: function(data){
                    console.log(data);
                }
            })
        }
    } 
});
```
