### ISSUE TITLE
INVISIBLE_RECAPTCHA_BADGEHIDE not hiding badge

### ISSUE THREAD

**Issue by hedii** [albertcht/invisible-recaptcha#65]
Hi, it seems the INVISIBLE_RECAPTCHA_BADGEHIDE env is doing nothing.

my .env:
````
INVISIBLE_RECAPTCHA_SITEKEY=my_key
INVISIBLE_RECAPTCHA_SECRETKEY=my_key
INVISIBLE_RECAPTCHA_BADGEHIDE=true
INVISIBLE_RECAPTCHA_DEBUG=false
````

my form:
```
`
/* ... */
{!! app('captcha')->render(LaravelLocalization::getCurrentLocale()) !!}
/* ... */
<button type="submit" class="btn btn-primary btn-rounded">
    submit
</button>
````

the result:
<img width="1495" alt="capture d ecran 2018-01-25 a 09 10 24" src="https://user-images.githubusercontent.com/5358048/35377544-e2546eec-01af-11e8-8509-63bd1db64622.png">

**Comment by albertcht** [comment]
Hi @hedii ,

You can use inspector to check if `display: none !important` is applied on your `.grecaptcha-badge` css class.

![](https://i.imgur.com/SYu18P2.png)

**Comment by hedii** [comment]
Hey @albertcht,

I already checked my env before submitting this issue (config is ok when dumped in a blade view).

The style tag with display none is in the rendered html of the page, but it looks like something is removing it from the dom on page load.

Maybe a side effect with Vuejs which is complaining about the captcha script tag in the page wrapper #app.

I am ok to close this issue because I put the required css myself in the head of the page, but maybe you should double check.

<img width="438" alt="capture d ecran 2018-01-29 a 09 53 27" src="https://user-images.githubusercontent.com/5358048/35501450-48510444-04da-11e8-9863-3486ac08a02a.png">

<img width="786" alt="capture d ecran 2018-01-29 a 09 42 44" src="https://user-images.githubusercontent.com/5358048/35501021-e20b04ba-04d8-11e8-820c-41d6868e9d92.png">

<img width="1221" alt="capture d ecran 2018-01-29 a 09 43 08" src="https://user-images.githubusercontent.com/5358048/35501026-e5687106-04d8-11e8-9b31-a163e1af1c4c.png">

**Comment by albertcht** [comment]
Hey @hedii ,

This package is not guaranteed compatible with Vue.js for the front-end side. It's highly not recommended to render raw HTML in your Vue app.

**Comment by hedii** [comment]
Yes, my form in rendered through laravel blade, but my layout have a #app div for vue (default laravel layout) and vue is activated on all pages. So there is no vue related stuff in the form.

**Comment by albertcht** [comment]
Got it, however there's nothing I could do since `display: none !important` style of `.grecaptcha-badge` is rendered successfully. There must be somewhere in your page effecting this behavior.  If you figure out what makes this happen please let me know.

**Comment by hedii** [comment]
Ok! thanks @albertcht
