### ISSUE TITLE
framework usage "vue"

### ISSUE THREAD

**Issue by ctf0** [albertcht/invisible-recaptcha#67]
https://github.com/albertcht/invisible-recaptcha/issues/48

issue is related to frameworks that doesnt allow script tags inside its container ex.**vue** so we have to move the captcha outside of it which means it will be outside of any form boundaries.

maybe a solution would be assigning an id to the form, and send it as a param to the captcha directive ex.
```blade
<form id='demo-form' action="?" method="POST">
      <button>Submit</button>
</form>

@captcha('#demo-form')
```

**Comment by albertcht** [comment]
Hi @ctf0 ,

Thanks for your valuable suggestion. In the beginning this package is designed without consideration for framework like Vue.js. And actually Vue.js also suggests developers not to manipulate the DOM. The better solution for invisible recaptcha with Vue.js you can consider the package like this one: [vue-invisible-recaptcha](https://github.com/MicroDroid/vue-invisible-recaptcha).

**Comment by ctf0** [comment]
thanx for the vue package link

**Comment by eduarguzher** [comment]
it should be considered again IMHO...

**Comment by ctf0** [comment]
@eduarguzher and for everyone else after the same issue, u actually dont need this package, here is a good tutorial https://itnext.io/how-to-use-google-recaptcha-with-vuejs-7756244400da 

basically all the recaptcha check is done client side so no need for the server side check
