### ISSUE TITLE
update for using with Laravel 5.6, please ;-)

### ISSUE THREAD

**Issue by ultimateBusiness** [albertcht/invisible-recaptcha#68]

**Comment by charlielangridge** [comment]
Please can you merge PR #69

**Comment by albertcht** [comment]
Yes, I've merged the pull request, and the released version is `v1.8.2`

**Comment by johnnymast** [comment]
It should not be a suggestion :( it should be priority (with all do respect). i might fork and packagist OR just do a pr .. how fast could you respond if i make a 5.6 pr ?

**Comment by johnnymast** [comment]
This is the most awesome package for what it does loads of us need it.

**Comment by johnnymast** [comment]
i just saw you updated it today! Good thanks i needed it yesterday and it didnt work (yet) your so awesome. Thanks a lot

**Comment by albertcht** [comment]
You're welcome.
