### ISSUE TITLE
INVISIBLE_RECAPTCHA_BADGEHIDE does not work

### ISSUE THREAD

**Issue by johnnymast** [albertcht/invisible-recaptcha#70]
Hello There,

I was trying to hide the badge on the bottom right but it didnt work like i wanted it to. Here is my .env file.

<img width="832" alt="schermafbeelding 2018-02-12 om 22 39 19" src="https://user-images.githubusercontent.com/121194/36121129-9a5c9dea-1045-11e8-9c80-d331bc8414b5.png">

And this is what i see in my frontend.

<img width="810" alt="schermafbeelding 2018-02-12 om 22 40 02" src="https://user-images.githubusercontent.com/121194/36121165-b3c36098-1045-11e8-8dc0-9421a835bd02.png">

In blade im using this.

<img width="451" alt="schermafbeelding 2018-02-12 om 22 46 25" src="https://user-images.githubusercontent.com/121194/36121477-95d96964-1046-11e8-9273-b16a3219f106.png">

The HTML you output is correct look at this.

<img width="1379" alt="schermafbeelding 2018-02-12 om 22 50 23" src="https://user-images.githubusercontent.com/121194/36121702-4d08972c-1047-11e8-8808-35b6346efdc7.png">

Im not 100% sure how but when i inspect the badge winch has class .grecaptcha-badge indeed. The style from the class is never applied to it. I don't understand why because the i have no other classes named .grecaptcha-badge and i don't ajax load any html or css code for styles and the captcha is loaded with the page by default. 

Just thinking might it be a race condition where the class in css is defined but the object is rendered via javascript later. It should not be i know because the css is defined before the badge is rendered but it still comes to mind ..

OR !! When the javascript renders it importants and other css rule  show the badge and that will over write your display: none rule. That must be it i think .. You can fix that with javascript and maybe add a section to your views and tell the users to yield the javascript code in the footer. Im going to test this now ..

Okey i got most working now with css but it still has a border like this 

```css
iframe[src^="https://www.google.com/recaptcha/api2/anchor"] {
  visibility: hidden;
}
```

This hides the badge BUT does not hide its border .. we need to investigate more.

I just figured it out to hide both the iframe internals and the border you need this javascript code. After the document loaded (so the iframe == the loaded as well)..

We need to do the below code because google adds inline style properties to the .grecaptcha-badge element. We could do without it if a stylesheet would be loaded after the DOM is ready but right now we cant so we need some javascript (so sad).

```javascript
document.addEventListener('DOMContentLoaded', function () {
  let box = document.querySelector('.grecaptcha-badge');
  box.style.boxShadow = 'none'
});
```

This will hide the google Recaptcha box  100%. It might be as well that you also set a display as none  (or visibilty:hidden) as that value on document ready. i Think the code evaluated singe you wrote it.. So its one ore the other both do it via javascript or half on half .. 

<img width="1219" alt="schermafbeelding 2018-02-12 om 23 52 14" src="https://user-images.githubusercontent.com/121194/36124341-f86714f6-104f-11e8-8366-18b20d1bf645.png">

Thanks for listening .. sleep well have a good day .. 

Johnny Mast...

**Comment by johnnymast** [comment]
love you to bits ..

**Comment by albertcht** [comment]
Hi @johnnymast ,

Is the source code you posted on the above [here](https://github.com/johnnymast/11min/blob/master/resources/views/contact/index.blade.php) ? I will take a look at this and try to figure it out in the few days.

**Comment by albertcht** [comment]
Hi @johnnymast ,

I tried to figure out why css style rendered by this package doesn't apply to your DOM of contact page, but I can't find a specific reason so far.

However, I find something interesting. It seems that somewhere in your `public/app.js` making `.grecaptcha-badge{display:none;!important}` disappeared in your rendered DOM.

If you try to remove `app.js` from your contact page or use the default [app.js](https://github.com/laravel/laravel/blob/master/public/js/app.js) provided by Laravel originally, you will see everything works properly.

So I think there must be somewhere in your `app.js` changing this behaviour.

**Comment by johnnymast** [comment]
I will double check my code.

**Comment by johnnymast** [comment]
well i came back to the project. it seems besides my hiding script (explained above) i didnt have any other wierd code except plain vue. Right now if i view the issues here i seems i was right about my claims. I suggest you review your project because i love it but there are some big issues with the google badge. I read it few times already i suggest you try my fix ..
