### ISSUE TITLE
recapctha ask verify every submit

### ISSUE THREAD

**Issue by Sarfroz** [albertcht/invisible-recaptcha#77]
hi, as i have also used other website forms with captcha,  they don't ask to verify recapctha with every submit. But here every time i click on submit i have to verify it. is it from google side or do i need to change some configuration.

**Comment by albertcht** [comment]
Hi @Sarfroz ,

There's a security preference in Recaptcha's setting page. You can try to set the level to `easiest`. 

![security-preference](https://i.imgur.com/lfUjRVM.png)

If you trigger the captcha multiple times in a short period, Google will judge you're a robot and ask you to verify you're human. This is normal, and there's no way to avoid it.

**Comment by johnnymast** [comment]
@Sarfroz this is normal to recaptcha. it has a timer and the timer will will decrease with every time you reload the form. If you are developing a form and testing it the recaptcha well notice and will get more strict with the next reload. What i do in development is disable the validation and enable it when your testing your form for real.
