### ISSUE TITLE
How to use multi-forms

### ISSUE THREAD

**Issue by marcelogarbin** [albertcht/invisible-recaptcha#81]
Hi, 
I've seen your multi-form branch, but I'd like to know how to use it correctly.
I have 1 form that always appears in the footer of the website (newsletter), and sometimes the contact form appears on other pages.

In that case, how do I call the recaptcha?
Can I use "@captcha()" in each form, or should I encode JS for face form?

**Comment by marcelogarbin** [comment]
I'm having this error after installing the "multi-forms" branch:

![image](https://user-images.githubusercontent.com/9335588/39600280-9eabda1c-4ef4-11e8-97a3-3ede54c634e7.png)

The error appears in this script
```
<script>var _renderedTimes,_captchaCallback,_captchaForms,_submitForm,_submitBtn;</script><script>var _submitAction=true,_captchaForm;</script><script>$.getScript('https://www.google.com/recaptcha/api.js?onload=_captchaCallback&render=explicit').done(function(data,status,jqxhr){_renderedTimes=$("._g-recaptcha").length;_captchaForms=$("._g-recaptcha").closest("form");_captchaForms.each(function(){$(this)[0].addEventListener("submit",function(e){e.preventDefault();_captchaForm=$(this);_submitBtn=$(this).find(":submit");grecaptcha.execute();});});_submitForm=function(){_submitBtn.trigger("captcha");grecaptcha.reset();if(_submitAction){_captchaForm.submit();}};_captchaCallback=function(){grecaptcha.render("_g-recaptcha_"+_renderedTimes,{sitekey:'6LeXGFcUAAAAAPnILx6jSDkyFEOPe3QLS-n07Cfg',size:'invisible',callback:_submitForm});}});</script>
<div class='_g-recaptcha' id='_g-recaptcha_1'></div>
```

**Comment by marcelogarbin** [comment]
@albertcht Would you help me?

**Comment by albertcht** [comment]
Hi @marcelogarbin ,

It looks like you didn't require jquery before calling `@captcha()`, did you?

**Comment by marcelogarbin** [comment]
Hi @albertcht , first thank you for your feedback.
That's right, I usually use the webpack to join all the JS and put it at the end of the tag body.
As it was at the end I did not pay attention to that. I put it in the beginning of the body and it worked.

But I am still in doubt about the operation.
I have 2 forms, 1 contact and 1 newsletter. One is in the center of the body, another in the footer.
When I send the data, I always use the request, in case:

RequestContato
```php
return [
            'g-recaptcha-response' => 'required|captcha',
            'nome'                 => 'required|alpha_spaces|max:255',
            'email'                => 'required|email',
            'telefone'             => 'required|regex:/\([1-9]{2}\)\040[0-9]{4}\-[0-9]{4,5}/',
            'mensagem'             => 'required|min:10',
        ];
```

RequestNewsletter
```php
return [
            'g-recaptcha-response' => 'required|captcha',
            'nome_newsletter'      => 'required|alpha_spaces|max:255',
            'email_newsletter'     => 'required|email',
        ];
```

When using multi-forms, is not it necessary to validate `g-recaptcha-response`?

Because when I try to send via the contact form, I get the following inputs:
![image](https://user-images.githubusercontent.com/9335588/39626831-f706f338-4f79-11e8-99d1-e348b30de9cc.png)

And in the case of the newsletter:
![image](https://user-images.githubusercontent.com/9335588/39626858-16d4cafa-4f7a-11e8-8b82-e134e072e95a.png)

What can this be? I'm not using AJAX.

**Comment by albertcht** [comment]
Hi @marcelogarbin ,

Sorry for the late response, I'm currently busy working on another project. I will reply to you in few days.

**Comment by albertcht** [comment]
Hi @marcelogarbin ,

`g-recaptcha-response` token should be taken to your request.  Can you listen the `captcha` event and dump your recaptcha token?

``` html
{!! Form::open(['url' => '/']) !!}
@captcha()
{!! Form::submit('Sumbit', ['id'=>'button_id']) !!}
{!! Form::close() !!}

<script type="text/javascript">
    $('#button_id').on('captcha', function(e) {
        console.log($("#g-recaptcha-response").val());
        _submitAction = false;
    });
</script>
```
