### ISSUE TITLE
Form not submitted

### ISSUE THREAD

**Issue by phpspider** [albertcht/invisible-recaptcha#91]
I've implemented this but my form is not submitted. Button type is submit.
In console I am getting error "uncaught exception: null"

The above is happening when I am clicking on Verify button in the captcha images.

**Comment by albertcht** [comment]
Can you please try to reproduce your issue on codepen? Like what I did here: https://codepen.io/albertcht/pen/MXraNr, that would be easier to debug. I only need your html redered by your frontend code.

**Comment by phpspider** [comment]
It's working in codepen.

**Comment by phpspider** [comment]
Following issue I am facing with my code.

recaptcha__en.js:251 Uncaught (in promise) null
hp @ recaptcha__en.js:251
(anonymous) @ recaptcha__en.js:249
nf @ recaptcha__en.js:71
jf @ recaptcha__en.js:71
b @ recaptcha__en.js:68

**Comment by albertcht** [comment]
Can you reproduce your error on codepen? Otherwise I don't have any clues about your issue.

**Comment by phpspider** [comment]
It's resolved now. I was not adding the id and name to my submit button.
