### ISSUE TITLE
Uncaught Error: Missing required parameters: sitekey

### ISSUE THREAD

**Issue by JamesPoel** [albertcht/invisible-recaptcha#94]
Console error:

Uncaught Error: Missing required parameters: sitekey
    at new es (recaptcha__en.js:402)
    at new ys (recaptcha__en.js:408)
    at Ks (recaptcha__en.js:416)
    at recaptcha__en.js:416
    at Array.forEach (<anonymous>)
    at Ls (recaptcha__en.js:416)
    at vs (recaptcha__en.js:421)
    at ws (recaptcha__en.js:408)
    at recaptcha__en.js:423
    at recaptcha__en.js:431

My INVISIBLE_RECAPTCHA_SITEKEY and INVISIBLE_RECAPTCHA_SECRETKEY env variables are set.

**Comment by jimmerioles** [comment]
I am also experiencing this issue, only happens in staging not in local.

**Comment by bhushangaykawad** [comment]
i am also getting same issue

**Comment by albertcht** [comment]
Which version of Laravel are you using?

**Comment by bhushangaykawad** [comment]
Laravel 5.7

**Comment by bhushangaykawad** [comment]
I hv figured it out.. but getting uncaught promise null error.. cant able to submit form at all..

**Comment by albertcht** [comment]
I can't figure it out until you give more specific description or example code.

**Comment by bhushangaykawad** [comment]
I did whatever things are in documentation.. but could not be able to send form data.. when i checked console . It had uncaught promise null error

**Comment by albertcht** [comment]
Unable to reproduce on a fresh new Laravel 5.7. See https://github.com/albertcht/invisible-recaptcha-example

BTW, are you using this package in a Vue.js project. This package doesn't support Vue.js. This issue will be closed shortly if there's still no reproducible details.
