### ISSUE TITLE
[HELP] Cannot test a form with ReCaptcha using Laravel Dusk

### ISSUE THREAD

**Issue by ludo237** [albertcht/invisible-recaptcha#95]
Hello.

I would like to say thank you for this amazing package, it's really useful in every aspect. That being said, I've a small problem testing an invisible ReCaptcha on a form using Laravel Dusk.

I've this method inside `CreatesApplication.php` file in `/tests`

``` PHP
    /**
     *
     */
    protected function withoutRecaptcha() : void
    {
        InvisibleReCaptcha::shouldReceive("verifyRequest")
            ->andReturnTrue();
        
        InvisibleReCaptcha::shouldReceive("verifyResponse")
            ->once()
            ->andReturnTrue();
    }
```

This works quiet well for Features test, because I only need to hit APIs and I can ignore the `g-recaptcha-response` input from the post request.

But if I want to test the form itself, using a browser test system like Laravel Dusk, of course this is not enough.

My current Dusk method is the following.

``` PHP

/** @test */
    public function a_guest_can_fill_the_registration_form()
    {
        $this->withoutRecaptcha();
        
        $this->browse(function (Browser $browser) {
            $browser->maximize()
                ->visit(new Register())
                ->assertPresent("input[name=g-recaptcha-response]")
                ->fillFormWithRandomData()
                ->submitForm()
                ->waitForReload()
                ->assertVisible(".alert.alert-success");
        });
    }
```

Straightforward stuff here, I call the register form, fill the data, submit it and check if an alert is in sight. Currently this doesn't work and I get this error:

``` BASH
There was 1 failure:

1) Tests\Browser\RegisterTest::a_guest_can_fill_the_registration_form
Element [body input[name=g-recaptcha-response]] is not present.
Failed asserting that false is true.

/app/vendor/laravel/dusk/src/Concerns/MakesAssertions.php:806
/app/vendor/laravel/dusk/src/Concerns/ProvidesBrowser.php:67
```

So the problem is clear: During the test the ReCaptcha input is not rendered thus it's impossible to hit it or even _fake_ it

Is there a way to render of fake the ReCaptcha in order to make it works with Laravel Dusk?

Thank you

**Comment by albertcht** [comment]
Hi @ludo237 ,

Because `g-recaptcha-response` is taken from Google's recaptcha response, I think you don't need to test that input field in Laravel Dusk.

**Comment by ludo237** [comment]
@albertcht that makes sense but the test will still fail even without the `assertPresent()` method.

The blade page is a simple form with `@captcha` directive on it.
