### ISSUE TITLE
5.7.* support in multi-forms

### ISSUE THREAD

**Issue by Shujee** [albertcht/invisible-recaptcha#98]
Can you please add 5.7.* support in multi-forms branch?

**Comment by Shujee** [comment]
And also update this in packagist?

**Comment by albertcht** [comment]
Hi @Shujee ,

Sure, as you wish.

**Comment by Shujee** [comment]
Thanks a ton.

**Comment by Shujee** [comment]
Don't know why, but this is not working for me. I have got two modal dialogs on my page, each one having its own captcha. Both connect to the server through ajax.
I'm currently working with only one of the modals. Captcha appears to connect to Google servers and receives 200 OK, but somehow **g-recaptcha-response** field doesn't get set, which results in failed validation on my server.
I have also made sure that both captchas are assigned different **id** (_g-recaptcha_1 and _g-recaptcha_2), so that it is not assigning response to the wrong div.

**Comment by Shujee** [comment]
My initial debugging suggests that it is **_renderedTimes** variable that hasn't been dealt with correctly. Google's response goes into the wrong response div; and that too doesn't contain the actual code. Can you please when you get a chance?

**Comment by Shujee** [comment]
This might be of some value:
https://stackoverflow.com/questions/30685443/google-recaptcha-not-posting-g-recaptcha-response

**Comment by Shujee** [comment]
Ignore my previous comments. I think I have managed to make it work. Thanks.
